name: Ping peri√≥dico a Render

on:
  schedule:
    - cron: "*/10 * * * *"  # cada 10 minutos
  workflow_dispatch:        # para lanzarlo manualmente

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer ping a Render
        run: |
          curl -sS https://TU-APP.onrender.com || echo "Fallo el ping"
