name: Ping periódico a Render

on:
  schedule:
    # Cada 10 minutos (ajusta como quieras)
    - cron: "*/10 * * * *"
  workflow_dispatch: # para ejecutarlo manualmente

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer ping a Render
        run: |
          curl -sS https://docdigital-demo.onrender.com || echo "Falló el ping"
<<<<<<< HEAD
=======


>>>>>>> fac6aeabc58f98f48628b8f0cf9a61dec3fc3f44
