name: Ping periódico a Render

on:
  schedule:
    # Cada 10 minutos (ajusta como quieras)
    - cron: "*/10 * * * *"
  workflow_dispatch: # para ejecutarlo manualmente

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer ping a Render
        run: |
          curl -sS https://https://docdigital-demo.onrender.com/ || echo "Falló el ping"

